#!/bin/bash

echo "Total de Containers em Execução: " `docker stats --format "." --no-stream | wc -l` 
docker stats --format "**Nome:** {{.Name}} **Uso de CPU**: {{.CPUPerc}} **Mem Usada**: {{.MemUsage}}\n" --no-stream
exit 0